### ISSUE TITLE
Blog Links not directing to correct website URL

### ISSUE THREAD

**Issue by 3xp11i** [PrasoonPratham/PrasoonPratham#1]
I don't know but for some reason, when I click on the blog posts links that are there on your Profile Readme (which automatically updates I guess) are not working properly, they are redirecting me to some strange place. 

I first noticed this on my Brave Browser, but then just to test I also tested it in a guest window to check if it was caused by any extension. But the results remain the same.

## Video Recording of the issue

https://user-images.githubusercontent.com/65062036/209153580-f59bd430-6cbd-4470-9675-3828930e3060.mp4

**Comment by 3xp11i** [comment]
I hope you find this a genuine issue and would be glad to help 😇

**Comment by PrasoonPratham** [comment]
Known issue that I'm working to fix. Thank you.

**Comment by 3xp11i** [comment]
Good to know that you know about this issue!
By the way, I wanted to talk to you a little, just had some little questions about career in tech, so I am sending you a message request on Twitter. I would be grateful if you accept to help me with your thoughts 😊

Thanks for your time!
